### ISSUE TITLE
加入阿里的aliyun-log-log4j2-appender的依赖启动报错

### ISSUE THREAD

**Issue by huangshengz** [aliyun/aliyun-log-log4j2-appender#13]
加入aliyun-log-log4j2-appender依赖，启动项目报空指针异常！
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.http.conn.ssl.SSLSocketFactory.<clinit>(SSLSocketFactory.java:153)
	at org.apache.http.impl.conn.SchemeRegistryFactory.createDefault(SchemeRegistryFactory.java:53)
	at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.<init>(ThreadSafeClientConnManager.java:102)
	at com.aliyun.openservices.log.http.comm.HttpFactory.createThreadSafeClientConnManager(HttpFactory.java:74)
	at com.aliyun.openservices.log.http.comm.HttpFactory.createHttpClient(HttpFactory.java:57)
	at com.aliyun.openservices.log.http.comm.DefaultServiceClient.<init>(DefaultServiceClient.java:38)
	at com.aliyun.openservices.log.Client.<init>(Client.java:427)
	at com.aliyun.openservices.log.Client.<init>(Client.java:452)
	at com.aliyun.openservices.log.Client.<init>(Client.java:357)
	at com.aliyun.openservices.log.Client.<init>(Client.java:333)
	at com.aliyun.openservices.log.producer.inner.ClientPool.buildClient(ClientPool.java:88)
	at com.aliyun.openservices.log.producer.inner.ClientPool.updateClient(ClientPool.java:48)
	at com.aliyun.openservices.log.producer.LogProducer.setProjectConfig(LogProducer.java:22)
	at com.aliyun.openservices.log.log4j2.LoghubAppender.start(LoghubAppender.java:119)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:266)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:547)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:619)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:636)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:231)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.commons.logging.LogAdapter$Log4jLog.<clinit>(LogAdapter.java:155)
	at org.apache.commons.logging.LogAdapter$Log4jAdapter.createLog(LogAdapter.java:122)
	at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:89)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
	at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:194)
	at cn.gz.ComapnyApplication.main(ComapnyApplication.java:10)
Caused by: java.lang.NullPointerException
	at org.apache.commons.logging.LogAdapter$Log4jLog.<init>(LogAdapter.java:160)
	at org.apache.commons.logging.LogAdapter$Log4jAdapter.createLog(LogAdapter.java:122)
	at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:89)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
	at org.apache.http.conn.ssl.AbstractVerifier.<init>(AbstractVerifier.java:61)
	at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<init>(AllowAllHostnameVerifier.java:44)
	at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<clinit>(AllowAllHostnameVerifier.java:46)
	... 29 more

注释掉依赖则一切正常！
 
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>2.5.0</version>
        </dependency>

**Comment by xiongdi9456** [comment]
同样的问题

**Comment by brucewu-fly** [comment]
您好，请问您的应用还引入了什么其他的库吗？如果有的话，请把您的 pom.xml 贴出来。

**Comment by xiongdi9456** [comment]
`<dependencies>

        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
        </dependency>
        
        <dependency>
            <groupId>com.lmax</groupId>
            <artifactId>disruptor</artifactId>
            <version>3.4.0</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>2.5.0</version>
        </dependency>
        <dependency>
            <groupId>com.aliyun.openservices</groupId>
            <artifactId>aliyun-log-log4j2-appender</artifactId>
            <version>0.1.10</version>
        </dependency>



        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
`

**Comment by xiongdi9456** [comment]
@brucewu-fly

**Comment by AhianZhang** [comment]
对于上面的问题，将 springBoot 版本降到 1.5.8.RELEASE 就能够正常运行了，
 springBoot 2.X 版本使用的日志是 spring-jcl ，假如要使用 slf4j 或者 log4j2 需要做桥接转换或者手动去排除 jcl 的依赖（并未尝试）

**Comment by chaolee50** [comment]
你好，springboot2 使用一下依赖可用
`		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-jcl</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
		</dependency>
		<dependency>
			<groupId>com.google.protobuf</groupId>
			<artifactId>protobuf-java</artifactId>
			<version>2.5.0</version>
		</dependency>
		<dependency>
			<groupId>com.aliyun.openservices</groupId>
			<artifactId>aliyun-log-log4j2-appender</artifactId>
			<version>0.1.11</version>
		</dependency>`

**Comment by chaolee50** [comment]
<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-jcl</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
		</dependency>
		<dependency>
			<groupId>com.google.protobuf</groupId>
			<artifactId>protobuf-java</artifactId>
			<version>2.5.0</version>
		</dependency>
		<dependency>
			<groupId>com.aliyun.openservices</groupId>
			<artifactId>aliyun-log-log4j2-appender</artifactId>
			<version>0.1.11</version>
		</dependency>

**Comment by chaolee50** [comment]
你好，springboot2 使用以下依赖可用

**Comment by chaolee50** [comment]
<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-jcl</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
		</dependency>
		<dependency>
			<groupId>com.google.protobuf</groupId>
			<artifactId>protobuf-java</artifactId>
			<version>2.5.0</version>
		</dependency>
		<dependency>
			<groupId>com.aliyun.openservices</groupId>
			<artifactId>aliyun-log-log4j2-appender</artifactId>
			<version>0.1.11</version>
		</dependency>

**Comment by StoneLittleSun** [comment]
我把

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

放到最后     </dependencies>  的上面一行，解决的这个问题。

**Comment by jol5** [comment]
请问，我的是springboot 2.2.4 加了单独使用log4j2没问题，用了以上配置依然报这个null

**Comment by jol5** [comment]
> 请问，我的是springboot 2.2.4 加了单独使用log4j2没问题，用了以上配置依然报这个null

加了排除spring-jcl,好像没起作用，在依赖里，依然能看到spring-jcl

**Comment by aoleiming** [comment]
> 桥接转换

请问能具体说明一下吗？也遇到同样的问题了，修改依赖依然没有用。
